name: CI

on:
    pull_request_target:
    push:
        branches: [master]

jobs:
    verify:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: 'package.json'
                  cache: 'npm'
            - run: npm ci
            - run: npm run release
            - run: npm run validate
            - run: npm run eslint
            - run: npm run test
            - run: npm run test:e2e
